Fix: Empty files and dirs will now be saved to ZIP
Mobica/innoextract-wasm pull request #58
Opened 2023-10-06 06:06 UTC by Michal-Ston-Mobica

Empty files and directories will no longer be omitted when creating the output ZIP.

2023-10-09 10:23 UTC, Rafal-Gorczewski-Mobica requested changes

2023-10-09 10:23 UTC, Rafal-Gorczewski-Mobica commented on src/wasm/extract.cpp
> +  std::string zipfile = output_dir + ".zip";
```suggestion
  const std::string zipfile = output_dir + ".zip";
```

2023-10-09 10:23 UTC, Rafal-Gorczewski-Mobica commented on src/wasm/extract.cpp
> +    if (extracted_n >= 0) {
Won't this always be true?

2023-10-09 14:51 UTC, Michal-Ston-Mobica commented
Fixed issues mentioned in review.

2023-10-10 09:15 UTC, Rafal-Gorczewski-Mobica approved these changes

2023-10-10 09:21 UTC, merged