[RND 201-202] exclude temporary files test
Mobica/innoextract-wasm pull request #96
Opened 2024-01-12 08:08 UTC by Anna-Majda-Mobica

2024-01-12 12:54 UTC, ewga requested changes

2024-01-12 12:54 UTC, ewga commented on tests/src/page_objects/locators/locators.py
> +OpeningFileText = '//pre[contains(text(),"file_4MB.exe")]'
This variable shouldn't be part of locators.py since it uses file specific name and can't be use by other tests. It should be defined as test variable.

2024-01-12 12:54 UTC, ewga commented on tests/tests/optionsTests.robot
> +    Wait Until Element Is Visible    ${OpeningFileText}
This test is part of another task and PR https://github.com/Mobica/innoextract-wasm/pull/93 and shouldn't be here.

2024-01-15 13:08 UTC, krzysztof-rodzaj-mobica approved these changes
Appears to be ok

2024-01-17 12:58 UTC, ewga approved these changes

2024-01-19 08:57 UTC, merged